"""

Django settings for b2bop_project project.
 
Generated by 'django-admin startproject' using Django 5.1.2.

"""
 
from pathlib import Path

from corsheaders.defaults import default_headers

import os

import mongoengine
 
# -------------------------------------------------------------------

# Base directory

# -------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent
 
# -------------------------------------------------------------------

# MongoDB connection

# -------------------------------------------------------------------

# Load Mongo URI from environment variable, or fallback to Atlas

MONGO_URI = os.getenv(
    'MONGO_URI',
    "mongodb+srv://petchimuthukumar:OKNCx63ChXs9PS9q@cluster1.epqhi7b.mongodb.net/user_management?retryWrites=true&w=majority&appName=Cluster1"
)
 
# Django-MongoEngine config

MONGODB_DATABASES = {

    'default': {

        'name': 'user_management',

        'host': MONGO_URI,

        'tz_aware': True,   # ensure timezone-aware datetimes

    }

}
 
# Also connect with mongoengine directly (for raw queries if needed)

mongoengine.connect(

    db="user_management",

    host=MONGO_URI,

    alias="default"

)
 
# -------------------------------------------------------------------

# Media & Static files

# -------------------------------------------------------------------

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
 
STATIC_URL = 'static/'
 
# -------------------------------------------------------------------

# Security

# -------------------------------------------------------------------

SECRET_KEY = 'django-insecure-3)*o)j&1$08q65k4vsn2-&%ymv!dfe4*#1d)1d4pnudal$)gw*'

DEBUG = True

ALLOWED_HOSTS = ["*"]
 
# -------------------------------------------------------------------

# CORS / CSRF

# -------------------------------------------------------------------

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True
 
CORS_ALLOWED_ORIGINS = [

    "https://b2bop-frontend-react.onrender.com",

    "http://localhost:3000",

    "http://192.168.30.191:4200",

    "https://b2-b-op-git-dev-lakshmi-lakshmis-projects-276e5906.vercel.app",

    "https://b2bop.netlify.app"

]
 
CSRF_TRUSTED_ORIGINS = [

    "http://localhost:3000",

    "https://b2bop-frontend-react.onrender.com",

    "http://192.168.30.191:4200",

    "https://b2-b-op-git-dev-lakshmi-lakshmis-projects-276e5906.vercel.app",

    "https://b2bop.netlify.app"

]
 
CORS_ALLOW_HEADERS = list(default_headers) + [

    'content-type',

]
 
# -------------------------------------------------------------------

# Installed Apps

# -------------------------------------------------------------------

INSTALLED_APPS = [

    'django.contrib.admin',

    'django.contrib.auth',

    'django.contrib.contenttypes',

    'django.contrib.sessions',

    'django.contrib.messages',

    'django.contrib.staticfiles',
 
    # Third-party

    'rest_framework',

    'rest_framework_simplejwt',

    'django_mongoengine',

    'django_mongoengine.mongo_auth',

    'corsheaders',
 
    # Local

    'user_management',

]
 
# -------------------------------------------------------------------

# Middleware

# -------------------------------------------------------------------

MIDDLEWARE = [

    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'b2bop_project.custom_mideleware.customMiddleware',  # custom middleware

]
 
# -------------------------------------------------------------------

# Templates

# -------------------------------------------------------------------

ROOT_URLCONF = 'b2bop_project.urls'
 
TEMPLATES = [

    {

        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.debug',

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]
 
WSGI_APPLICATION = 'b2bop_project.wsgi.application'
 
# -------------------------------------------------------------------

# Authentication

# -------------------------------------------------------------------

AUTHENTICATION_BACKENDS = (

    'django_mongoengine.mongo_auth.backends.MongoEngineBackend',

)
 
# -------------------------------------------------------------------

# Password validation

# -------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [

    {

        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',

    },

    {

        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',

    },

]
 
# -------------------------------------------------------------------

# Internationalization

# -------------------------------------------------------------------

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
 
# -------------------------------------------------------------------

# Default PK

# -------------------------------------------------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
 
# -------------------------------------------------------------------

# Email Services

# -------------------------------------------------------------------

MAILGUN_API_KEY = os.getenv('MAILGUN_API_KEY')

MAILGUN_DOMAIN = os.getenv('MAILGUN_DOMAIN')

SENDGRID_API_KEY = os.getenv('SENDGRID_API_KEY')
 
# -------------------------------------------------------------------

# Cron (disabled for now)

# -------------------------------------------------------------------

# CRON_CLASSES = [

#     'user_management.operations.user_operations.CheckPendingOrders',

# ]

 